# Generated by Django 3.2.4 on 2021-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
